export const ROUTE_NAMES = {
  LOGIN: 'login',
  REGISTER: 'register',
  HOME: 'home',
  NOTES: 'notes',
  NOTE_EDITOR: 'note-editor',
  CALENDAR: 'calendar',
  PLAN_FORM: 'plan-form',
  COUNTDOWN_DETAIL: 'countdown-detail',
  ME: 'me',
  EDIT_PROFILE: 'edit-profile',
  SETTINGS: 'settings',
  FRIENDS: 'friends',
  TASKS: 'tasks',
  MANAGE_FOLDERS: 'manage-folders',
  ACTIVE_SESSION: 'active-session',
  STUDY_STATS: 'study-stats',
  SUBJECTS: 'subjects',
} as const;

export const ROUTE_PATHS = {
  LOGIN: '/login',
  REGISTER: '/register',
  HOME: '/',
  NOTES: '/notes',
  NOTE_EDITOR: '/notes/:id',
  CALENDAR: '/calendar',
  PLAN_FORM: '/calendar/plan/:id?',
  COUNTDOWN_DETAIL: '/calendar/countdown/:id',
  ME: '/me',
  EDIT_PROFILE: '/me/edit-profile',
  SETTINGS: '/me/settings',
  FRIENDS: '/me/friends',
  TASKS: '/tasks',
  MANAGE_FOLDERS: '/tasks/manage-folders',
  ACTIVE_SESSION: '/study/active',
  STUDY_STATS: '/study/stats',
  SUBJECTS: '/study/subjects',
} as const;
